// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatermarkedPodAutoscaler) DeepCopyInto(out *WatermarkedPodAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatermarkedPodAutoscaler.
func (in *WatermarkedPodAutoscaler) DeepCopy() *WatermarkedPodAutoscaler {
	if in == nil {
		return nil
	}
	out := new(WatermarkedPodAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WatermarkedPodAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatermarkedPodAutoscalerList) DeepCopyInto(out *WatermarkedPodAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WatermarkedPodAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatermarkedPodAutoscalerList.
func (in *WatermarkedPodAutoscalerList) DeepCopy() *WatermarkedPodAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(WatermarkedPodAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WatermarkedPodAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatermarkedPodAutoscalerSpec) DeepCopyInto(out *WatermarkedPodAutoscalerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatermarkedPodAutoscalerSpec.
func (in *WatermarkedPodAutoscalerSpec) DeepCopy() *WatermarkedPodAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(WatermarkedPodAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatermarkedPodAutoscalerStatus) DeepCopyInto(out *WatermarkedPodAutoscalerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatermarkedPodAutoscalerStatus.
func (in *WatermarkedPodAutoscalerStatus) DeepCopy() *WatermarkedPodAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(WatermarkedPodAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}
