// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscaler":       schema_pkg_apis_datadoghq_v1alpha1_WatermarkedPodAutoscaler(ref),
		"github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscalerSpec":   schema_pkg_apis_datadoghq_v1alpha1_WatermarkedPodAutoscalerSpec(ref),
		"github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscalerStatus": schema_pkg_apis_datadoghq_v1alpha1_WatermarkedPodAutoscalerStatus(ref),
	}
}

func schema_pkg_apis_datadoghq_v1alpha1_WatermarkedPodAutoscaler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatermarkedPodAutoscaler is the Schema for the watermarkedpodautoscalers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscalerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscalerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscalerSpec", "github.com/CharlyF/watermarkedpodautoscaler/pkg/apis/datadoghq/v1alpha1.WatermarkedPodAutoscalerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_datadoghq_v1alpha1_WatermarkedPodAutoscalerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatermarkedPodAutoscalerSpec defines the desired state of WatermarkedPodAutoscaler",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_datadoghq_v1alpha1_WatermarkedPodAutoscalerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WatermarkedPodAutoscalerStatus defines the observed state of WatermarkedPodAutoscaler",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
