apiVersion: datadoghq.com/v1alpha1
kind: WatermarkedPodAutoscaler
metadata:
  name: example-watermarkedpodautoscaler
spec:
  # Add fields here
  maxReplicas: 3
  minReplicas: 1
  highWatermark: 7
  lowWatermark: 40
  tolerance: 0.2
  scaleTargetRef:
    kind: Deployment
    name: nginx
  metrics:
  - type: External
    external:
      metricName: nginx.net.request_per_s
      metricSelector:
        matchLabels:
          kube_container_name: nginx
      targetValue: 9

