apiVersion: datadoghq.com/v1alpha1
kind: WatermarkedPodAutoscaler
metadata:
  name: example-watermarkedpodautoscaler
spec:
  # Add fields here
  maxReplicas: 3
  minReplicas: 1
  tolerance: 0.2
  scaleTargetRef:
    kind: Deployment
    name: nginx
  metrics:
  - type: External
    external:
      highWatermark: 42000000
      lowWatermark: 39000000
      metricName: docker.mem.rss
      metricSelector:
        matchLabels:
          env: datad0g.eu
          image_name: mongo
