apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermarkedpodautoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: watermarkedpodautoscaler
  template:
    metadata:
      labels:
        name: watermarkedpodautoscaler
    spec:
      serviceAccountName: watermarkedpodautoscaler
      containers:
        - name: watermarkedpodautoscaler
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - watermarkedpodautoscaler
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "watermarkedpodautoscaler"
